### ISSUE TITLE
Support CSON manifest format

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#168]
YAML looks a bit cleaner. It could be the default manifest format, and keep JSON for backwards compatibility. Example:

```yaml
name: "somelib"
version: "1.0.0"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
url: "https://github.com/craftr-build/craftr"
dependencies:
  "craftr.lang.cxc": "*"
options:
  sourcedir: "string"
  debug: "bool"
```
